name: Deploy Container CloudFormation 1

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  deploy:
    name: Deploy CloudFormation Stack
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Validate CloudFormation Template
      run: |
        aws cloudformation validate-template --template-body file://Web-Container.yaml

    - name: Deploy CloudFormation Stack
      run: |
        aws cloudformation deploy \
          --template-file Web-Container.yaml \
          --stack-name NodeJSAppStack \
          --capabilities CAPABILITY_NAMED_IAM
